### ISSUE TITLE
Missing 0.6 release tag

### ISSUE THREAD

**Issue by eskimor** [messense/if-addrs#2]
Hi there again!

If I may suggest to provide tags for released versions of this library. I just noticed that the 0.6 release on crates apparently is not the same as current master, but also did not find a 0.6 tag to see what commit actually is released on crates.

Also, a new release with the latest fixes would be awesome!

**Comment by messense** [comment]
Please use [v0.6.1](https://crates.io/crates/if-addrs/0.6.1) instead, I'll yank 0.6.0.

**Comment by eskimor** [comment]
Thank you @messense !
